### ISSUE TITLE
[Leveler] Disable leveler

### ISSUE THREAD

**Issue by Dragonias** [fixator10/Fixator10-Cogs#121]
Would there be a way to "disable" the Leveler as I've noticed it's always creating a database even if a server doesnt use the level system which basicly wastes unecesarry space and basicly causes "tracking" 

Prehaps have it off by default and a command to turn it on

Thanks in Advance!

**Comment by Apoo711** [comment]
What if a server forgets a turn it on?

**Comment by fixator10** [comment]
You can disable and enable leveler via `[p]lvladmin toggle` command.

*On `abc` branch, just disable cog via `[p]command disablecog`*
