### ISSUE TITLE
[PersonalRoles] Role icon support

### ISSUE THREAD

**Issue by Cabbidachi** [fixator10/Fixator10-Cogs#122]
Discord is currently slowly rolling out a feature that lets you upload icons for roles. Since the PersonalRoles Cog lets people customize their own role i wonder if there is some way to also enable that people can upload their own icon for their personal role.

**Comment by Cabbidachi** [comment]
It seems to spread more and more. It also has reached my server now. What i can note now is that it only accepts uploaded images or custom emotes. The Discord official emotes don't seem to be allowed.

**Comment by fixator10** [comment]
Ye, its released now.

Will try to implement it somewhere about tommorow.

**Comment by fixator10** [comment]
Added support for role icons, but since Discord decided to fuck me up, and didnt provided any option to test paid  features, im unable to check for any bugs anymore.

Please report if you find anything weird/not working.

**Comment by Cabbidachi** [comment]
alrighty
so far it looks like it works how its supposed to work. The bot is able to access the icon setting of the role system and is able to change the role icon no problem. Not tested it yet with an actual image but emotes work.

**Comment by Cabbidachi** [comment]
Feature seems fully functional. No issues found. Thank you again for integrating it ^w^
