### ISSUE TITLE
[Leveler] Can't load the cog in Red 3.2.2

### ISSUE THREAD

**Issue by GamerGirl1995** [fixator10/Fixator10-Cogs#20]
After updating to the latest version of Red (being 3.2.2)

the Leveler cog has stopped functioning and can't be loaded any longer.

These are the errors displayed in the Console:

http://prntscr.com/qp5dbh (Screenshot link)

Bare in mind i do have Pillow installed and Numpy (the correct versions)
hopefully this gets fixed, and if it is something on my side. please help me fix it.

Thank you for your amazing cogs.

**Comment by fixator10** [comment]
Try `[p]pipinstall pillow>=6.2.1`. Its seems, that versions lower than 6.2.1 doesn't support py3.8.
(python-pillow/Pillow#4141)

**Comment by GamerGirl1995** [comment]
It loads again, thanks and it seems to work. however the only things still left in the console is this error: 

http://prntscr.com/qpb3h7 (Screenshot Link)

**Comment by fixator10** [comment]
This just means that `scipy` lib doesnt load properly, maybe installed incorrectly, or not installed at all. scipy is used only for `[p]lvlset <levelup/profile/rank> color auto` feature.
You can install [scipy](https://www.scipy.org/install.html) or just use leveler without it.
