### ISSUE TITLE
[Captcha] Cannot complete challenge using capital letters

### ISSUE THREAD

**Issue by AztralMenu** [fixator10/Fixator10-Cogs#205]
When users type in the captcha with cap letters as the image shows the bot counts it a fail unless they lowercase it.

**Comment by madebylydia** [comment]
Hello,
Sorry for keeping you waiting, I have other events going on that makes me unable to be totally present at Red.

I seems unable to reproduce your issue, by using capital letters, I am able to validate the Captchas.
Can you try giving me more context on how this issue happens?

Also, by looking at the source code, both the code and the user's input are validated in uppercase, so it shouldn't matter.
